#!/usr/bin/env bash

get_credentials()
{
    local -n loc_UNAME="$1"
    local -n loc_PWORD="$2"
    local pwcopy

    # Use prompt variables to access length for cursor reposition:
    local pwprompt1="Enter a password: "
    local pwprompt2="Renter the password: "

    echo -n "Enter a username: "
    read loc_UNAME

    while true; do
        echo -n "${pwprompt1}"
        read loc_PWORD
        echo -n "[1F[${#pwprompt1}C"
        echo "${loc_PWORD//?/-}"
        
        echo -n "${pwprompt2}"
        read pwcopy
        echo -n "[1F[${#pwprompt2}C"
        echo "${pwcopy//?/-}"
        
        if [ "$pwcopy" == "$loc_PWORD" ]; then
            return 0
        else
            loc_PWORD=
            pwcopy=
            echo "Passwords mismatch; try again."
        fi
    done

    return 1
}

declare username
declare userpassword

# Call the function with the _names_ of the current-scope's variables
# in order that the function can return the user-entered values therein:
if get_credentials "username" "userpassword"; then
    echo "The user name is ${username} and the password is ${userpassword}"
else
    echo "Failed to get username and password."
fi
