#!/usr/bin/env bash

# Waits for and returns single keypress, even if it is
# represented by multiple characters.
get_keypress()
{
    # IFS characters will be invisible to 'read', so:
    local IFS=''

    local prompt="${1:=Press any key}"

    # Array to collect chars in case of multi-char keypress
    local -a chars=( )
    
    # Wait for a keypress (-n 1), save to array
    local keychar
    read -n 1 -s -p "${prompt}" keychar
    chars=( "$keychar" )

    # Collect additional characters if available, especially for escape characters
    while read -t 0; do
        read -n 1 keychar
        chars=( "${chars[@]}" "$keychar" )
    done

    # empty IFS so array is joined without delimiters
    echo "${chars[*]}"
}

# Examples of possible get_keypress returns:

# Enter escape character in EMACS with C-q, ESC
# (see documentation: info emacs -n "Inserting Text")
declare keypress_down_arrow='[B'
declare keypress_up_arrow='[A'

# Other control characters can be tested with $'\c.':
declare keypress_ctrl_n=$'\cn'
declare keypress_ctrl_p=$'\cp'




# Demonstrate usage:

declare keystroke

while [ "$keystroke" != "q" ]; do
    keystroke=$( get_keypress "Press q to quit. " )

    case "$keystroke" in
        "$keypress_down_arrow") echo "You pressed down-arrow" ;;
        "$keypress_up_arrow" )  echo "You pressed up arrow" ;;
        "$keypress_ctrl_n" )    echo "You pressed control-n" ;;
        "$keypress_ctrl_p" )    echo  "You pressed control-p" ;;
        *)
            if [ "${keystroke:0:1}" = "" ]; then
                keystroke="^[${keystroke:1}"
            fi
            echo "keystroke is [32m${keystroke}[m" ;;
    esac

done
