#!/usr/bin/env bash

source list_toggler

show_choices()
{
    local map_name="$1"
    local -n choices="$map_name"
    local key
    local -i value
    for key in "${!choices[@]}"; do
        value="${choices[$key]}"
        if [ "$value" -ne 0 ]; then
            echo "Selected $key"
        fi
    done
}

############################
###### Customizations ######
############################

# Change line display by overriding default toggler_print_choice() function
toggler_print_choice()
{
    local key="$1"
    local -i value="$2" hilite="$3"
    local lineval="$key"

    if [ "$value" -eq 0 ]; then
        lineval="[31;1m$lineval NOT selected"
    else
        lineval="[32;1m$lineval selected"
    fi

    if [ "$hilite" -ne 0 ]; then
        lineval="[43m${lineval}"
    fi

    echo "$lineval[m"
}

# If desired, add introduction text that precedes options (default is no intro text):
T_INTRO="Select one or more of the following options:"$'\n'

# Override prompt that follows options by setting the T_PROMPT variable:
T_PROMPT="Get help with '?', use 'x' to execute, 'q' to quit."

# Allow upper- or lower-case letter for execute and quit
# TGROUP_EXEC=$'x|X'
# TGROUP_QUIT=$'q|Q'

# Define new UP or DOWN group of keys (leave out TAB/shift-TAB options).
# Notice that the TKEYS_XXX string must change to match the TGROUP_XXX:
TGROUP_UP=$'\e\\[A' # Up-arrow, shift-tab
TKEYS_UP="Up-arrow"
TGROUP_DOWN=$'\e\\[B|\n'  # Down-arrow, tab, Enter
TKEYS_DOWN="Down-arrow|Enter"

############
### MAIN ###
############

# declare regular array of keys (to maintain order),
declare -a packages=( apache mariadb php )
# and an associative array to store user responses
declare -A guidance=( [apache]=1 [mariadb]=1 )

if toggler "packages" "guidance"; then
    show_choices "guidance"
fi

echo
