#!/usr/bin/env bash

source list_toggler

show_choices()
{
    local map_name="$1"
    local -n choices="$map_name"
    local key
    local -i value
    for key in "${!choices[@]}"; do
        value="${choices[$key]}"
        if [ "$value" -ne 0 ]; then
            echo "Selected $key"
        fi
    done
}

############################
###### Customizations ######
############################

# Change line display by overriding default toggler_print_choice() function
toggler_print_choice()
{
    local key="$1"
    local -i value="$2" hilite="$3"
    local lineval="$key"

    if [ "$value" -eq 0 ]; then
        lineval="[31;1m$lineval NOT selected"
    else
        lineval="[32;1m$lineval selected"
    fi

    if [ "$hilite" -ne 0 ]; then
        lineval="[43m${lineval}"
    fi

    echo "$lineval[m"
}

# Override prompt by setting the T_PROMPT variable:
T_PROMPT="Get help with '?', use 'q' to quit."

# Add introduction text if desired (default is no intro text):
T_INTRO="Select one or more of the following options:"$'\n'

############
### MAIN ###
############

# declare regular array of keys (to maintain order),
declare -a packages=( apache mariadb php )
# and an associative array to store user responses
declare -A guidance

if toggler "packages" "guidance"; then
    show_choices "guidance"
fi
