#!/usr/bin/env bash

source sources/include

# @def Script template for creating selectable test
#
# Create functions that can be called to perform tests.
#
# The library function lui_list_runner() will clear the
# screen before and after running the test.
#
# The test functions need to pause before returning or
# the output will disappear.

to_continue() { read -n1 -p Press\ any\ key\ to\ continue.; }

test_one()
{
    echo "This is test one."
    to_continue
}

test_two()
{
    echo "This is test two."
    to_continue
}



###########################
#          MAIN           #
#  Execution Begins Here  #
###########################

# Setup for unexpected termination
save_console_state_hide_cursor
trap restore_console_state_show_cursor SIGINT
trap restore_console_state_show_cursor EXIT


# @def The menu lui_list array
#
# lui_list_runner() only uses the first two columns
# of a row, the first column is what is displayed in the
# list interaction, and the second column is the function
# to call.
declare -a MAIN_MENU=(
    2 0
    "perform first test"   test_one
    "perform second test"  test_two
)
lui_list_init "MAIN_MENU"

# Optionally define text to sit atop the test menu.
declare -a paras
bind_paragraphs "paras" <<EOF
Select a test and press ENTER to perform the test.

Press ESC or 'q' to terminate the program."
EOF

# The following function call will run the whole program.
# The `paras` parameter is optional.
lui_list_runner "MAIN_MENU" "paras"

