#!/usr/bin/env bash

declare -a Include_Sources=( small_stuff boxes )
source sources/include

reset_screen

draw_box 10 10 10 10
draw_box 10 20 20 40

declare str="This is a message."
declare -i row col rows=5 cols=$(( "${#str}" + 2 ))
get_block_centering_values "row" "col" "rows" "cols"
draw_box "$row" "$col" "$rows" "$cols"
set_cursor_position $(( row+2 )) $(( col+1 ))
echo -n "$str"

# Move cursor out of box
echo
