#!/usr/bin/env bash

declare -a Include_Sources=( small_stuff keypress list_ui debugging csv_file )
source sources/include

to_continue() { read -n1 -p "Press any key"; }

test_parse_csv_line()
{
    local -a csv_lines=(
        "Master Category,Subcategory,Date,Location,Payee,Description,Payment Method,Amount"
        "here,\"Plymouth,MN\",there,everywhere"
        "\"here, there, and everywhere\",my home,your home,chez sa maison"
        "monopoly,scrabble,boggle,candyland,\"snakes, and ladders\""
    )

    local -a row
    local line el

    for line in "${csv_lines[@]}"; do
        array_from_csv_line "row" "$line"
        reset_screen
        echo "For [33;1m$line[m, there are ${#row[@]} elements"
        for el in "${row[@]}"; do
            echo "   $el"
        done
        to_continue
    done
}

test_read_csv_file()
{
    local filename="Chuck_CreditCard.csv"
    local -a ll_data
    local -a ll_raw

    if csv_read_file "ll_data" "ll_raw" "$filename"; then
        echo "Read the file, baby!"
        echo "There are ${ll_data[1]} rows of ${ll_data[0]} fields."
        to_continue
    fi
}

test_write_csv_file()
{
    local filename="Chuck_CreditCard.csv"
    local newfilename="${filename/./1.}"
    local -a ll_data
    local -a ll_raw

    if csv_read_file "ll_data" "ll_raw" "$filename"; then
        echo "There are ${ll_data[1]} rows of ${ll_data[0]} fields."
        echo "About to write contents to $newfilename" 
        write_csv_to_file "${newfilename}" "ll_data"
    else
        echo "failed to open '$filename'"
    fi

    to_continue
}

declare -a MAIN_MENU=(
    2 0
    "test parse_csv_line" test_parse_csv_line
    "test read_csv_file"  test_read_csv_file
    "test write_csv_file" test_write_csv_file
)
lui_list_init "MAIN_MENU"

lui_list_runner "MAIN_MENU"

